// <auto-generated />
namespace Download_Vouchery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class auto_increment_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auto_increment_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201604201230337_auto_increment_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
